spring:
  application:
    name: yikou-ai-feiwu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.101:3306/yikou_ai?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 815256031Hc!
  session:
    store-type: redis
    timeout: 2592000
  data:
    redis:
      host: 192.168.10.101
      port: 6379
      ttl: 3600
      password:
      database: 0
  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.feiwu.yikouai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# 运行项目需要配置以下资源密钥，部分大模型生成能力可能较弱，可用自行调整
# AI配置
#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: <你的api-key>
#      model-name: deepseek-v3
#      log-requests: true
#      log-responses: true
#      max-tokens: 8192
#    #      strict-json-schema: true
#    #      response-format: json_object
#    streaming-chat-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: <你的api-key>
#      model-name: qwen3-coder-flash
#      max-tokens: 8192
#      log-requests: true
#      log-responses: true
#    reasoning-streaming-chat-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: <你的api-key>
#      model-name: qwen3-coder-flash
#      log-requests: true
#      log-responses: true
#      max-tokens: 3678
#      temperature: 0.1
#    routing-chat-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: <你的api-key>
#      model-name: deepseek-v3
#      log-requests: true
#      log-responses: true
#      max-tokens: 8192
#
## 添加 COS 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: <你的云对象桶地址>
#    secretId: <你的云对象存储secretId>
#    secretKey: <你的云对象存储secretKey>
#    region: <你的云对象存储地域>
#    bucket: <你的云对象桶名>
#
## Pexels 图片搜索配置
#pexels:
#  api-key: <你的Pexels api-key>
#
## 阿里云 DashScope 配置
#dashscope:
#  api-key: <你的阿里云灵积 api-key>
#  image-model: wan2.2-t2i-flash
