spring:
  application:
    name: yikou-ai-feiwu

server:
  port: 8122
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.feiwu.yikouai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

